const express = require("express")
const { getHomePage, getContact, getCategory, getAboutPage, getAccountFavorite, getAccountMyAds, getAccountProfileSetting, getAdListingList, getAdListingGrid, getAdsDetails, getBlogGrid, getBlogLeftSide, getBlog, getDashboard, getFAQ, getForgotPassword, getIndex2, getIndex3, getLogin, getOfferMessage, getPayment, getPostads, getPricing, getPrivacySetting, getRegister, getService, getSinglepost, getTestimonial, getAddCart, getCheckout, addCart, updateCart, removeCartItem } = require("../controller/getUserController")
const verifyToken = require("../middleware/verifyToken")
const router = express.Router()

router.get("/", verifyToken, getHomePage)
router.get("/contact", verifyToken, getContact)
router.get("/category", verifyToken, getCategory)
router.get("/about", verifyToken, getAboutPage)
router.get("/account-favourite-ads", verifyToken, getAccountFavorite)
router.get("/account-myads", verifyToken, getAccountMyAds)
router.get("/profile-setting", verifyToken, getAccountProfileSetting)
router.get("/adlistinggrid", verifyToken, getAdListingGrid)
router.get("/adlistinglist", verifyToken, getAdListingList)
router.get("/ads-details/:detailsId", verifyToken, getAdsDetails)
router.get("/blog-grid", verifyToken, getBlogGrid)
router.get("/blog-left", verifyToken, getBlogLeftSide)
router.get("/blog", verifyToken, getBlog)
router.get("/dashboard", verifyToken, getDashboard)
router.get("/faq", verifyToken, getFAQ)
router.get("/forget-password", verifyToken, getForgotPassword)
router.get("/index-2", verifyToken, getIndex2)
router.get("/index-3", verifyToken, getIndex3)
router.get("/login", verifyToken, getLogin)
router.get("/offermessages", verifyToken, getOfferMessage)
router.get("/payment", verifyToken, getPayment)
router.get("/post-ads", verifyToken, getPostads)
router.get("/pricing", verifyToken, getPricing)
router.get("/privacy-policy", verifyToken, getPrivacySetting)
router.get("/register", verifyToken, getRegister)
router.get("/service", verifyToken, getService)
router.get("/single-post", verifyToken, getSinglepost)
router.get("/testimonial", verifyToken, getTestimonial)
router.get("/getcart", verifyToken, getAddCart)
router.get("/checkout", verifyToken, getCheckout)
router.get("/postcart/:id",verifyToken, addCart)
module.exports = router